global:
 scrape_interval: 15s
 scrape_timeout: 10s
 evaluation_interval: 15s

alerting:
 alertmanagers:
 - static_configs:
   - targets: ['alertmanager:9093']  # Update this with your Alertmanager address
   scheme: http
   timeout: 10s
   api_version: v2
rule_files:
 - "alert.rules.yml" 
scrape_configs:
 - job_name: 'prometheus'
   honor_timestamps: true
   metrics_path: /metrics
   static_configs:
   - targets: ['prometheus:9090']
 - job_name: 'node'
   honor_timestamps: true
   metrics_path: /metrics
   static_configs:
   - targets: ['<server ip>:9100']
