apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-metrics
  template:
    metadata:
      labels:
        app: flask-metrics
    spec:
      containers:
        - name: flask-container
          image: metric-web-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "5m"
            limits:
              memory: "128Mi"
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-metrics-service
  labels: 
    app: service-flask-metrics
spec:
  selector:
    app: flask-metrics
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
